[package]
name = "dlpack"
version = "0.1.1"
authors = ["PENGUINLIONG <admin@penguinliong.moe>"]
repository = "https://github.com/PENGUINLIONG/dlpack.rs.git"
description = "Rust language binding for DLPack."
license = "Apache-2.0"

[dependencies]
