[package]
name = "dlpack"
version = "0.1.0"
authors = ["PENGUINLIONG <admin@penguinliong.moe>"]
repository = "https://github.com/PENGUINLIONG/dlpack.rs.git"
description = "Rust language binding for DLPack."

[dependencies]
